### PR TITLE
[#61] Add current time to home app

### PR DESCRIPTION
**Pull request by thibault-ml**
This change displays the current time in the home app, depending on the configured timezone.
The time is synced via NTP when a wifi connection is established.
The timezone can be changed via the "Change Timezone" app which is also part of this change.

### CODE REVIEW

**Comment by thibault-ml** [comment]
@mattbrejza Can do indeed.

**Comment by thibault-ml** [comment]
@mattbrejza Done :-)

**Comment by mattbrejza** [comment]
Sorry to be a pain, but I've gone and moved most of home/main.py into home/home.py

If you could make that quick change to your code this should then be good to merge :)

**Comment by thibault-ml** [comment]
@mattbrejza no worries, done now :)

**Comment by thibault-ml** [comment]
@mattbrejza Anything else needing change or reviewed for this to be merged?

**Comment by mattbrejza** [comment]
Sorry for the delay, I've been playing about with your changes and they work well, however if the NTP server is inaccessible or the NTP operation otherwise fails, then the badge will hang. It is apparently possible for non-blocking socket operations (not sure if we have any examples), or alternatively the NTP query could be moved to the timezone app.

**Comment by thibault-ml** [comment]
@mattbrejza Good point! I'll try to have a look :-)

**Comment by thibault-ml** [comment]
@mattbrejza Added a timeout of 2 seconds :). Given this code is only called just after we've just connected to a WiFi AP, I think the 2 seconds is acceptable. It's not like it's going to call it in a loop :-) (unless the wifi keeps connecting and disconnecting).

**Comment by Jonty** [comment]
Tested and working

**Pull request merged**
