### PR TITLE
Adapt quick_launch and file_loader to app module

### PR DESCRIPTION
**Pull request by marekventur**
lots of the stuff around walking folders, reading properties, etc is already in the module. Switching to that saves about 100 lines of code \o/

* the "pinned" field is not storing the app name (username~appname) instead of the full path to the main.py, so clean your database.json
* categories are parsed from the list of existing apps rather than hardcoded
* quick_launcher: avoid duplication for the 8 buttons
* "run()" is not part of the app model

### CODE REVIEW

**Comment by mattbrejza** [comment]
We should make all ugfx.poll()s consistent while we're at it

**Comment by thinkl33t** [comment]
We cant merge this as is - I've just done a clean install of this, and every app is now broken:

- [ ] Snake no longer starts (exception crash) ```NameError: name 'ugfx' is not defined```
- [ ] App Library no longer starts (exception crash) 
```  File "apps/app_library/main.py", line 65, in main_menu
NameError: name 'clear' is not defined```
- [ ] Chname no longer starts (whole badge freezes, white screen)
- [ ] Chwifi no longer starts (exception crash) ```NameError: name 'ugfx' is not defined```
- [ ] Home should not appear in the all apps list (its a bit meta)
- [ ] Logger no longer starts (badge freezes, white screen)
- [ ] test_app1 no longer starts (badge freezes, white screen)
- [ ] test_app1 no longer starts (badge freezes, white screen)

**Comment by marekventur** [comment]
I've fixed most of those issues, but the branch needs a rebase. I'll do the bootstrap stuff first and then I come back to it

**Comment by marekventur** [comment]
@thinkl33t rebased and all issues fixed.

**Comment by thinkl33t** [comment]
Apps all start now, but dont seem to be receiving any joystick input.

**Comment by thinkl33t** [comment]
Text on First Boot dialog button is unreadable.

**Comment by thinkl33t** [comment]
The "Welcome to EMF camp" popup now shows over the top of the splash screen (needs a clear?), and the text doesn't fit on it.

**Comment by thinkl33t** [comment]
This branch is dead

**Pull request closed without merging**
